#!/bin/bash

if [ $# == 0 ] ; then
  echo "usage: ./arxivpost [arxiv-id] [title] [comments]"
  echo "usage: ./arxivpost [arxiv-id] [date]"
  exit
fi

if [ $# == 2 ] ; then
  ./fetch.pl "$1" "__DATE__$2__ARXIV__TITLE" | ./genpost " "
fi


if [ $# == 3 ] ; then
  ./fetch.pl "$1" "$3" | ./genpost "$2"
fi

