#!/usr/bin/perl

# generate post from arxiv link
#

use List::MoreUtils 'first_index'; 

$title=$ARGV[0];
$arxiv=$ARGV[1];
$strip_title=$title;
$strip_title=~s/[^a-zA-Z]/-/g;

@months = ("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Oct","Nov","Dec");

use Time::Piece;

my $t = Time::Piece->new();
$sys_year = $t->year;

# content: fetch from arxiv
$content="";

while (<STDIN>) {
  if (/(([0-9]+)\/([0-9][0-9])\/([0-9][0-9]))/) {
    $fulldate = $1;
    $year=$2;
    $month_num=$3;
    $day=$4;
  } elsif (/((Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Oct|Nov|Dec)[a-z]*\ ([0-9]+),\ ([0-9]+))/) {
    $fulldate = $1;
    $month=$2;
    $day = $3;
    $year = $4;
    $month_num = first_index { /$month/ } @months;
    $month_num ++;
  } elsif (/((Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Oct|Nov|Dec)[a-z]*\ ([0-9]+))/) {
    $fulldate = $1;
    $month=$2;
    $day = $3;
    $year = $sys_year;
    $month_num = first_index { /$month/ } @months;
    $month_num ++;
    $fulldate = $fulldate.", $year";
  } elsif (/(http.*\.\.\.)/) {
    print "\n\n\n****** Skipping $1\n\n\n";
    $content = "$content\n\n\n";
  } else {
    $str = $_;
    $str =~ s/\n/\n\n/g;
    $str =~ s/\xEF\xBF\xBC/\n\n\n/;
    $str =~ s/\?fbclid.+//;
    $str =~ s/(http[^\s]+)/\[$1\]\($1\)/g;
    $str =~ s/(\.COM)/$1\n\n\n/;
    if ($str =~ /shared\ a\ /) {
      $str = "\#\#\# quote \n\n$str\n";
    }
    if ($str =~ /^\s*Vincent\ Boucher\s*$/) {
      $str = "\#\#\# quote \n\n$str\n";
    }
    $content = "$content$str";
  }
}

if (length($fulldate)<1) {
  print "\n\n\n **** Date string error: [$fulldate]. Aborting\n";
  exit;
}

if (length($month_num)<2) {
  $month_num = "0$month_num";
}
if ($day<10) {
  $day= "0$day";
}

print "\n\n***$fulldate\n";
$filename = "$year-$month_num-$day-$strip_title.markdown";

if (-f $filename) {
  print "\n\n\n **** $filename exists. Overwriting. \n";
  open(FP,"> $filename");
} else {
  open(FP,"> $filename");
}

print FP <<EOF;
---
layout: post
title:  "$title"
date:   $fulldate
categories: none
---

$content 

EOF

close(FP);

print $content;
