#!/usr/bin/perl

# generate post from facebook 
#
# Example:  
# 
# February 23, 2020  · 
#UBER AI lab's generative teaching network (GTN) : https://eng.uber.com/generative-teaching-networks/
#Basic idea: build deep neural networks that generate synthetic data and learn, so that good architecture can be found fast before training on real data.
# Jeff Clune, Ken Stanley et al.

use List::MoreUtils 'first_index'; 

$title=$ARGV[0];
$strip_title=$title;
$strip_title=~s/[^a-zA-Z]/-/g;

@months = ("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Oct","Nov","Dec");


use Time::Piece;

my $t = Time::Piece->new();
$sys_year = $t->year;

# content: from stdin

$content="";

while (<STDIN>) {
  if (/((Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Oct|Nov|Dec)[a-z]*\ ([0-9]+),\ ([0-9]+))/) {
    $fulldate = $1;
    $month=$2;
    $day = $3;
    $year = $4;
    $month_num = first_index { /$month/ } @months;
    $month_num ++;
  } elsif (/((Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Oct|Nov|Dec)[a-z]*\ ([0-9]+))/) {
    $fulldate = $1;
    $month=$2;
    $day = $3;
    $year = $sys_year;
    $month_num = first_index { /$month/ } @months;
    $month_num ++;
    $fulldate = $fulldate.", $year";
  } else {
    $str = $_;
    $str =~ s/\n/\n\n/g;
    $str =~ s/\xEF\xBF\xBC/\n\n\n/;
    $str =~ s/\?fbclid.+//;
    $str =~ s/(http[^\s]+)/\[$1\]\($1\)/g;
    $str =~ s/(\.COM)/$1\n\n\n/;
    if ($str =~ /shared\ a\ /) {
      $str = "\#\#\# quote \n\n$str\n";
    }
    $content = "$content$str";
  }
}

if (length($fulldate)<1) {
  print "\n\n\n **** Date string error: [$fulldate]. Aborting\n";
  exit;
}

if ($month_num<10) {
  $month_num = "0$month_num";
}
if ($day<10) {
  $day= "0$day";
}

print "\n\n***$fulldate\n";
$filename = "$year-$month_num-$day-$strip_title.markdown";

if (-f $filename) {
  print "\n\n\n **** $filename exists. Overwriting. \n";
  open(FP,"> $filename");
} else {
  open(FP,"> $filename");
}

print FP <<EOF;
---
layout: post
title:  "$title"
date:   $fulldate
categories: none
---

$content 

EOF

close(FP);

print $content;
