#!/bin/bash
cp *.* scratch
cd scratch
m4 -P year.m4 | ../fixhtml > ../../_includes/pub_year.html
m4 -P topic.m4 | ../fixhtml > ../../_includes/pub_topic.html
m4 -P medium.m4 | ../fixhtml > ../../_includes/pub_medium.html
cd ..
